name: CD

on: [push, workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CD_HOST }}
          username: ${{ secrets.CD_USERNAME }}
          key: ${{ secrets.CD_KEY }}
          port: ${{ secrets.CD_PORT }}
          script: |
            cd /home/ubuntu/sites/ai-portfolio-backend

            # âœ… Safe directory pour Git
            git config --global --add safe.directory /home/ubuntu/sites/ai-portfolio-backend

            echo "ğŸ”„ Pulling latest code..."
            if [ ! -d ".git" ]; then
              git clone https://github.com/SebMZI/ai-portfolio-backend.git .
            else
              git pull
            fi

            echo "ğŸ³ Stopping previous container..."
            docker stop ai_portfolio_backend || true
            docker rm ai_portfolio_backend || true

            echo "ğŸ³ Building and deploying..."
            docker build -t ai_portfolio_backend .

            echo "ğŸš€ Running container..."
            docker run -d -p 3001:3001 \
              -e GEMINI_API_KEY=${{ secrets.API_KEY }} \
              -e CLIENT_URL=${{ secrets.CLIENT_URL }} \
              --name ai_portfolio_backend \
              --restart unless-stopped \
              ai_portfolio_backend

            echo "âœ… Deployment complete!"
